services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres_container
    environment:
      - POSTGRESQL_USERNAME=${POSTGRESQL_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/bitnami/postgresql
volumes:
  postgres_data:
